### ISSUE TITLE
[投诉评论]

### ISSUE THREAD

**Issue by heishi8** [zjuchalaoshi/chalaoshi#14]
### 投诉页面链接

https://chalaoshi.buzz/t/3496/#

### 投诉评论内容

2022年3月，两名已通过考研复试，导师确认为黄慧的学生果断放弃入学资格，并为第二年的考研做准备。 言已至此，慎重！
发布于 2022.05.24  [投诉](https://chalaoshi.buzz/t/3496/#)

### 你的身份

评论涉及

### 为什么这条评论不合适

2022年3月考研同学均已入学。
考研一般3月底以后，同学老师双向选择，自己沟通、自己确认。
5月，2022考研同学未进组，开学后才陆续进组。

**Comment by zjuchalaoshi** [comment]
Keep. We are unable to conduct fact-checking for individual comments. If you believe the comment in question contains inaccuracies, we encourage you to respond by providing more detailed and accurate information in a new comment. We trust that the audience is capable of discerning and forming their own judgments.
