### ISSUE TITLE
[新老师]

### ISSUE THREAD

**Issue by 213edr** [zjuchalaoshi/chalaoshi#19]
### 老师姓名

Robert Holmes

### 所在学院

国际联合学院

### 补充信息

![Uploading 微信图片_20241029135710.jpg…]()

**Comment by 213edr** [comment]
海宁校区著名英语老师

**Comment by zjuchalaoshi** [comment]
added https://chalaoshi.buzz/t/10733/ 

zju link https://its.intl.zju.edu.cn/zh-hans/node/874025
