### ISSUE TITLE
[新老师]

### ISSUE THREAD

**Issue by YujayPan** [zjuchalaoshi/chalaoshi#23]
### 老师姓名

侯庆春

### 所在学院

国际联合学院

### zju.edu.cn 网页链接

https://person.zju.edu.cn/houqingchun

### 补充信息

侯庆春博士2021年于清华大学电机工程与应用电子技术系获博士学位，导师康重庆教授（IEEE Fellow，系主任，国家杰青），合作老师张宁教授（教育部人才计划），同年入职阿里巴巴集团。他于2019年8月-2020年8月赴美国华盛顿大学联合培养，导师Daniel Kirschen教授（IEEE Fellow, Donald W. and Ruth Mary Close Professor）。侯博士的博士论文提出了稀疏斜决策树及其集成算法，提出了数据驱动的电力系统安全稳定规则提取及内嵌优化运行的一般理论与方法，提取的规则具有高精度、可解释、易于内嵌优化运行的特点，应用于青海、江苏电网等。博士论文成果被电机工程学报[《优博说》](https://mp.weixin.qq.com/s/DyHrQL5WFMoovEzoWVKoGQ)报道、[《Proceedings of IEEE》](https://ieeexplore.ieee.org/abstract/document/9864118)发表、清华大学电机系90周年[学术论坛](https://www.eea.tsinghua.edu.cn/info/1038/5205.htm)第一期分享。

在加入浙江大学之前，侯博士于2021年7月-2024年7月在阿里巴巴集团担任算法专家、阿里星、高级讲师。在阿里期间，他结合结合强化学习、Transformer等深度学习模型实时性的特点及传统优化算法的理论优势研发了TAM技术，领导团队基于TAM开发了大规模实时组合优化求解器Laser，能够实时地求解阿里巴巴集团业务中各类大规模NP-hard VRP问题，成功应用于淘宝买菜、盒马、天猫超市、天猫国际、AliExpress等。他同时研究大模型技术在电商、供应链、物流等领域的应用。其中，TAM技术发表于人工智能顶会[ICLR](https://openreview.net/pdf?id=6ZajpxqTlQ)，Laser在《全球物流技术大会》[分享并报道](https://mp.weixin.qq.com/s/C09G2w5dZN5Lh4cP2XtmqA)。

他曾获阿里星、日内瓦国际发明展金奖、IEEE iSPEC excellent paper award等荣誉与称号。在教学方面，他获得阿里巴巴第二届极客大赛五强讲师，讲授的课程《Transformer及其高效变体算法》在集团内部获得广泛关注，截止目前约1000人选修。

他的论文主要发表于顶刊《Proceedings of IEEE》、《IEEE Transactions on Power Systems》、《IEEE Transactions on Smart Grid》及人工智能顶会ICLR等。担任《IEEE Transactions on Power Systems》等顶刊及ICLR、ICML、NeurIPS、AAAI等人工智能顶会审稿人。

主要研究方向包括：人工智能及运筹优化、AI驱动的智能优化决策、高比例新能源电力系统优化运行、规划、安全稳定及决策、智慧供应链及物流

此外，招收电气工程或人工智能方向博士后、博士（直博或普博）、科研助理，欢迎联系~

**Comment by zjuchalaoshi** [comment]
added https://chalaoshi.buzz/t/10732/
