### ISSUE TITLE
[新老师]

### ISSUE THREAD

**Issue by yerik123** [zjuchalaoshi/chalaoshi#25]
### 老师姓名

张帆

### 所在学院

光华法学院

### zju.edu.cn 网页链接

https://person.zju.edu.cn/0022421

**Comment by zjuchalaoshi** [comment]
added https://chalaoshi.buzz/t/10730/

Please note that we are currently unable to handle duplicate names effectively.

person.zju source: 光华法学院, 计算机
our data: 竺可桢学院, 信息与电子工程学院, 农业与生物技术学院, 光华法学院 (added)
