### ISSUE TITLE
[新老师]

### ISSUE THREAD

**Issue by Wurao-liu** [zjuchalaoshi/chalaoshi#26]
### 老师姓名

苏冬

### 所在学院

就业指导与服务中心

### 补充信息

今年带了职业生涯规划课程。

**Comment by zjuchalaoshi** [comment]
added, confirmed by http://jsgzb.zju.edu.cn/_upload/article/files/cb/2a/eacae24d4623aa821c309e1ad9b5/1a400756-0347-4e68-ac77-68020821a099.xlsx
