### ISSUE TITLE
[投诉评论]

### ISSUE THREAD

**Issue by AlabTNT** [zjuchalaoshi/chalaoshi#4]
### 投诉页面链接

https://chalaoshi.buzz/t/3418/

### 投诉评论内容

真的垃圾老师，不如我们北大俞建江

### 你的身份

路人

### 为什么这条评论不合适

冒犯老师

**Comment by zjuchalaoshi** [comment]
Keep this comment. We trust that the audience is capable of discerning and forming their own judgments.
