### ISSUE TITLE
[投诉评论]

### ISSUE THREAD

**Issue by rucszl** [zjuchalaoshi/chalaoshi#42]
### 投诉页面链接

https://chalaoshi.buzz/t/9374/##205190

### 投诉评论内容

讲课内容比较专业，可以看出老师学问很深，给分比较中肯，可以选。
不过细节见人品，感觉讲话有点傲慢，会区别对待学生，这很难评价

### 你的身份

路人

### 为什么这条评论不合适

上过老师的课，感觉老师并没有傲慢，和学生很亲近会有很多互动，如果评论者觉着老师傲慢的话难道要老师像教幼儿园小朋友那样教学吗，如果傲慢的话应该会高高在上的看待学生，自顾自的讲，怎么会与学生去互动呢。

**Comment by zjuchalaoshi** [comment]
The content in question does not involve personal attacks nor does it cross ethical boundaries.
We are unable to conduct fact-checking for individual comments. If you believe the comment in question contains inaccuracies, we encourage you to respond by providing more detailed and accurate information in a new comment. We trust that the audience is capable of discerning and forming their own judgments.
