### ISSUE TITLE
[投诉评论]

### ISSUE THREAD

**Issue by R-Y-Yan** [zjuchalaoshi/chalaoshi#49]
### 投诉页面链接

https://chalaoshi.buzz/t/9035/##200380

### 投诉评论内容

我用他倒模的飞机杯

### 你的身份

路人

### 为什么这条评论不合适

我认为热评第二条的“我用他倒模的飞机杯”过于低俗，不适合用于评价一位老师的师德师风或教学水平。

**Comment by zjuchalaoshi** [comment]
deleted
