### ISSUE TITLE
[投诉评论] 该评论涉及恶毒的人身攻击

### ISSUE THREAD

**Issue by foam-111** [zjuchalaoshi/chalaoshi#5]
### 投诉页面链接

https://chalaoshi.buzz/t/9307/#

### 投诉评论内容

垃圾老师，胖的和猪一样还美女老师，真搞笑
![Snipaste_2024-09-14_08-34-01](https://github.com/user-attachments/assets/8325d208-84bb-4f63-84d1-e15a9d6de5bc)

### 你的身份

评论者

### 为什么这条评论不合适

差评意义不明且涉及外貌攻击。

**Comment by zjuchalaoshi** [comment]
thanks for the report, comment deleted
