### ISSUE TITLE
[投诉评论]

### ISSUE THREAD

**Issue by k77-hrl** [zjuchalaoshi/chalaoshi#50]
### 投诉页面链接

https://chalaoshi.de/t/10180/#206382

### 投诉评论内容

蠹僵疯就是浙大饮稀悦，理由如下
饮稀悦对着美国日本卖国求荣，蠹僵疯要把整个浙大出卖给科大
饮稀悦在美国和日本当着狗腿子和背景板四处走穴，而蠹僵疯在科大，无锡，还有各种它自己有钱赚的地方，一样飞来飞去四处走穴
饮稀悦把劳动者都污蔑成黑社会，把韩国民众都打成流氓，蠹僵疯凭借一己之力拉低了67656人中每个人的学历，调研学院时一副高高在上的官僚姿态，对着学生一边拖时间折磨一边还自带痛苦面具，而且迎新晚会这种学生集体活动上也自带痛苦面具的对口型。另外，蠹僵疯对于下级对待师生的各种不干人事更是听之任之，摆明了一副把师生都当成春竹的架势。
饮稀悦已经被弹劾了，蠹僵疯什么时候能享受这种普天同庆的待遇呢

### 你的身份

路人

### 为什么这条评论不合适

鉴证疯狗乱咬

**Comment by zjuchalaoshi** [comment]
deleted
- Use of derogatory language.
- Potential for defamation.
- Inflammatory and hostile tone.
