### ISSUE TITLE
[新老师]

### ISSUE THREAD

**Issue by CaoJH0** [zjuchalaoshi/chalaoshi#6]
### 老师姓名

黄建国

### 所在学院

生命科学学院

### zju.edu.cn 网页链接

https://person.zju.edu.cn/Jianguo_Huang

### 补充信息

![image](https://github.com/user-attachments/assets/daa35ff5-20d0-43a7-bebd-60229762780f)
该老师开课包括《野外生态学》、《生物地理学》和《生物学野外综合实习》，与化学系老师有重名，需要调整

**Comment by zjuchalaoshi** [comment]
added https://chalaoshi.buzz/t/10735/ Please note that we are currently unable to handle duplicate names effectively.
