### ISSUE TITLE
[投诉评论]

### ISSUE THREAD

**Issue by aewrwdw** [zjuchalaoshi/chalaoshi#7]
### 投诉页面链接

https://chalaoshi.buzz/t/10372/

### 投诉评论内容

首先，祝賀陳師姐入職浙大生科院，由衷地為她感到高興。我讀博期間與陳師姐在中山大學有一段交集，她當時也在讀博。我以一個過來人的視角很負責地跟各位學弟學妹們說：她是那種很有拼勁的「女漢子」，將實驗室的重擔挑在自己身上，是個對課題和老師很忠誠和負責的人。然而，她往往也扮演著實驗室的「刺頭」角色。記得她當時為了課題的進展，不惜在老師面前給另一個博士後（也是我的師兄）使絆子，最後排擠掉師兄，成功上位。師兄在我剛進實驗室期間幫了我很多，見到我總是笑臉相迎，雖然之後沒有太多工作以外的交集，但聽到他辭職離開的消息，我還是非常震驚。之後，風聲走漏以後，我們整個實驗室從此都不敢得罪陳師姐了。我也是對她恭恭敬敬。有一天因為與她產生了一點小誤會，晚上都睡不安穩，第二天還送了一些小心意給她（雖然我不是很喜歡這套人情世故，但對她只能如此），她才平息了怒火，當然挨她幾句風涼話也是不可避免，最後幸運地保住了老師對我的信任。最後發表一些個人愚見，她在讀博期間確實有一些成果，但確實有恃寵而驕之嫌，仗著自己受到的恩寵，給師兄上眼藥，更別說她的師弟師妹們，更多是受到她的各種批評。而且，有些批評和要求很無理，比如晚上十點之前不能離開實驗室之類的，不然就會被她「打嘴炮」。後來，她博士畢業以後離開實驗室，整個實驗室的環境清淨了許多。所以，各位浙大的學弟學妹們，選導要謹慎啊！將來有一天你們要選擇去陳師姐的實驗室，希望我說的這段肺腑之言對你們有所幫助。

### 你的身份

路人

### 为什么这条评论不合适

评论不实，存在人身攻击，本站的本意是针对老师授课情况开设，但是陈老师尚未进行教学工作，却受到了恶意中伤，希望屏蔽或删除

**Comment by zjuchalaoshi** [comment]
We are unable to conduct fact-checking for individual comments. If you believe the comment in question contains inaccuracies, we encourage you to respond by providing more detailed and accurate information in a new comment. We trust that the audience is capable of discerning and forming their own judgments.
