### ISSUE TITLE
[投诉评论]这是一条非理性的意见

### ISSUE THREAD

**Issue by sduwujian** [zjuchalaoshi/chalaoshi#9]
### 投诉页面链接

https://chalaoshi.buzz/t/1248/

### 投诉评论内容

“垃圾大学写作，给分超低，而且不说明白。”

### 你的身份

评论者

### 为什么这条评论不合适

这里所写的“垃圾”完全是一种不理性的评论，涉及人身攻击。

**Comment by zjuchalaoshi** [comment]
The content in question does not involve personal attacks nor does it cross ethical boundaries.
We are unable to conduct fact-checking for individual comments. If you believe the comment in question contains inaccuracies, we encourage you to respond by providing more detailed and accurate information in a new comment. We trust that the audience is capable of discerning and forming their own judgments.
